"""Initial migration

Revision ID: 89936f2ad37a
Revises: 
Create Date: 2026-09-28 19:14:35.241225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89936f2ad37a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('fields_detected', sa.Integer(), nullable=False),
    sa.Column('fields_filled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_fields_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index('ix_activities_user_created', 'activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_activities_website_domain'), 'activities', ['website_domain'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('website_domain', sa.String(length=255), nullable=False),
    sa.Column('website_field', sa.String(length=100), nullable=False),
    sa.Column('govconnect_field', sa.String(length=50), nullable=False),
    sa.Column('selector_query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'website_domain', 'website_field', name='uq_user_domain_field')
    )
    op.create_index(op.f('ix_mappings_id'), 'mappings', ['id'], unique=False)
    op.create_index('ix_mappings_user_domain', 'mappings', ['user_id', 'website_domain'], unique=False)
    op.create_index(op.f('ix_mappings_user_id'), 'mappings', ['user_id'], unique=False)
    op.create_index(op.f('ix_mappings_website_domain'), 'mappings', ['website_domain'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('work_address', sa.Text(), nullable=True),
    sa.Column('income', sa.String(length=100), nullable=True),
    sa.Column('npwp', sa.String(length=50), nullable=True),
    sa.Column('bpjs_number', sa.String(length=50), nullable=True),
    sa.Column('driver_license', sa.String(length=100), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('document_photos', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_mappings_website_domain'), table_name='mappings')
    op.drop_index(op.f('ix_mappings_user_id'), table_name='mappings')
    op.drop_index('ix_mappings_user_domain', table_name='mappings')
    op.drop_index(op.f('ix_mappings_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_activities_website_domain'), table_name='activities')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index('ix_activities_user_created', table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
